version: "3.8"

networks:
  backend:

services:
  onlinestore.db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: onlinestore.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:   
      - backend
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

  onlinestore.api:
    image: ${DOCKER_REGISTRY-}onlinestoreapi
    container_name: onlinestore.api
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: src/OnlineStore.API/Dockerfile
    depends_on:
      - onlinestore.db
    networks:
      - backend
    volumes:
      - ./src/OnlineStore.API:/app 
      - ~/.aspnet/https:/root/.aspnet/https:ro

volumes:
  mssql-data: