services:
  onlinestore.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: netcodehub/onlinestoreapi:v1
    container_name: onlinestore.api
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=onlinestore.db,1433;Database=OnlineStoreDb;User Id=sa;Password=Root1234;Trusted_Connection=False;TrustServerCertificate=true
    depends_on:
      - onlinestore.db
    networks:
      - my_network

  onlinestore.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: onlinestore.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root1234
      - MSSQL_PID=Developer
    ports:
      - "2000:1433"
    networks:
      - my_network
    volumes:
      - mssql-data:/var/opt/mssql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak_onlinestore
    command: start-dev
    ports:
      - 18085:8080
    environment:
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mssql-data:
